#ifndef Error_H
#define Error_H

//TOKEN ERROR
#define ERR_SYSTEM_ERROR          10
#define ERR_INVALID_INSTRUCTION   20
#define ERR_INVALID_OPERAND       21
#define ERR_INVALID_STRING		    30
#define ERR_INVALID_CHAR	   	    32
#define ERR_INVALID_INTEGER       41
#define ERR_INVALID_FLOAT         42
#define ERR_INVALID_IDENTIFIER    50
#define ERR_INVALID_OPERATOR      51


//FILE ERROR
#define ERR_FILE_NOT_EXIST        80
#define ERR_FILE_INVALID          81
#define ERR_INVALID_COMMEND_LINE  82
#define ERR_INVALID_LINE          83
#define ERR_VHDL_IDENTIFIER       85
#define ERR_INVALID_DESCRIPTION   86
#define ERR_INVALID_ATTRIBUTE     87
#define ERR_COMPONENT_NAME_FORMAT 90
#define ERR_GENERIC_PARAMETER     91
#define ERR_USE_STATEMENT         92
#define ERR_PORT_DESCRIPTION      93
#define ERR_INVALID_PINTYPE       94
#define ERR_INVALID_PORTDIMENSION 95
#define ERR_INVALID_RANGETYPE     96
#define ERR_VALUE                 97
#define ERR_PRINTING_PORTDESC     98
#define ERR_MULTIPLE_DECLARE      99
#define ERR_INVALID_PORTNAME      100

//will change
#define ERR_INVALID_TYPE            102
#define ERR_INVALID_STRING_TYPE     103


//pin mapping
#define ERR_INVALID_PIN_MAP_STATEMENT 101
#define ERR_INVALID_PINDESC_FORMAT     104
#define ERR_INVALID_PINDESC            105
#define ERR_INVALID_PORTMAP_FORMAT     106
#define ERR_INVALID_PORTNAME_FORMAT    107
#define ERR_INVALID_PINMAPPING_FORMAT  108

//Instrction length and boundary Length
#define ERR_INVALID_INSTRUCTION_LENGTH  110
#define ERR_INVALID_BOUNDARY_LENGTH     111

//SCAN PORT IDENTIFICATION
#define ERR_INVALID_SCAN_PORT_TYPE        112
#define ERR_INVALID_TAP_SCAN_CLOCK_FORMAT 113
#define ERR_INVALID_TAP_SCAN_IN_FORMAT    114
#define ERR_INVALID_TAP_SCAN_MODE_FORMAT  115
#define ERR_INVALID_TAP_SCAN_OUT_FORMAT   116
#define ERR_INVALID_TAP_SCAN_RESET_FORMAT 117

// Component comformance
#define ERR_INVALID_COMPONENT_COMFORMANCE_FORMAT 118

// Boundary Register
#define ERR_INVALID_BOUNDARY_REGISTER 120

#endif // Error_H
